config/routes.rb
Rails.application.routes.draw do
  root 'black_fridays#index'
  resources :black_fridays
  resources :homes
  resources :pples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/black_friday.rb
class BlackFriday < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/black_fridays_controller.rb
class BlackFridaysController < ApplicationController
  before_action :set_black_friday, only: [:show, :edit, :update, :destroy]

  # GET /black_fridays
  # GET /black_fridays.json
  def index
    @black_fridays = BlackFriday.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /black_fridays/1
  # GET /black_fridays/1.json
  def show
  end

  # GET /black_fridays/new
  def new
    @black_friday = BlackFriday.new
  end

  # GET /black_fridays/1/edit
  def edit
  end

  # POST /black_fridays
  # POST /black_fridays.json
  def create
    @black_friday = BlackFriday.new(black_friday_params)

    respond_to do |format|
      if @black_friday.save
        format.html { redirect_to @black_friday, notice: 'Black friday was successfully created.' }
        format.json { render :show, status: :created, location: @black_friday }
      else
        format.html { render :new }
        format.json { render json: @black_friday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /black_fridays/1
  # PATCH/PUT /black_fridays/1.json
  def update
    respond_to do |format|
      if @black_friday.update(black_friday_params)
        format.html { redirect_to @black_friday, notice: 'Black friday was successfully updated.' }
        format.json { render :show, status: :ok, location: @black_friday }
      else
        format.html { render :edit }
        format.json { render json: @black_friday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /black_fridays/1
  # DELETE /black_fridays/1.json
  def destroy
    @black_friday.destroy
    respond_to do |format|
      format.html { redirect_to black_fridays_url, notice: 'Black friday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_black_friday
      @black_friday = BlackFriday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def black_friday_params
      params.require(:black_friday).permit(:user_id, :product_id, :gender, :age, :occupation, :city_category, :stay_in_current_city_years, :marital_status, :product_category_1, :product_category_2, :product_category_3, :purchase)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
   
  end

end

app/controllers/pples_controller.rb
class PplesController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_fridays_helper.rb
module BlackFridaysHelper
end

app/views/black_fridays/_form.html.erb
<%= form_with(model: black_friday, local: true) do |form| %>
  <% if black_friday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(black_friday.errors.count, "error") %> prohibited this black_friday from being saved:</h2>

      <ul>
      <% black_friday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <%= form.label :user_id %>
          <%= form.text_field :user_id %>
        </div>
        <div class="input-field col s6">
          <%= form.label :product_id %>
          <%= form.text_field :product_id %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= form.label :gender %>
          <%= form.text_field :gender %>
        </div>
        <div class="input-field col s6">
          <%= form.label :age %>
          <%= form.number_field :age %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= form.label :city_category %>
          <%= form.text_field :city_category %>
        </div>
        <div class="input-field col s6">
          <%= form.label :stay_in_current_city_years %>
          <%= form.text_field :stay_in_current_city_years %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= form.label :marital_status %>
          <%= form.text_field :marital_status %>
        </div>
        <div class="input-field col s6">
          <%= form.label :purchase %>
          <%= form.text_field :purchase %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s3">
          <%= form.label :product_category_1 %>
          <%= form.text_field :product_category_1 %>
        </div>
        <div class="input-field col s3">
          <%= form.label :product_category_2 %>
          <%= form.text_field :product_category_2 %>
        </div>
        <div class="input-field col s3">
          <%= form.label :product_category_3 %>
          <%= form.text_field :product_category_3 %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= form.label :marital_status %>
          <%= form.text_field :marital_status %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= form.label :occupation %>
          <%= form.text_field :occupation %>
        </div>
      </div>

      </div>
    </form>
  </div>

  <div class="actions container">
    <%= form.submit class: "waves-effect waves-light btn" %>
  </div>

<% end %>

<%= javascript_tag do %>
  M.updateTextFields();
<% end %>

app/views/black_fridays/edit.html.erb
<h1>Editing Black Friday</h1>

<%= render 'form', black_friday: @black_friday %>
</br>
<div class="container">
  <%= link_to 'Show', @black_friday, class: "waves-effect waves-light btn" %> |
  <%= link_to 'Back', black_fridays_path, class: "waves-effect waves-light btn" %>
</div>

app/views/black_fridays/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Black Fridays</h3>
<%= link_to 'Back', homes_path, class: "waves-effect waves-light btn" %>
<%= link_to 'New', new_black_friday_path, class: "waves-effect waves-light btn", style: "float: right;" %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Occupation</th>
      <th>City category</th>
      <th>Stay in current city years</th>
      <th>Marital status</th>
      <th>Product category 1</th>
      <th>Product category 2</th>
      <th>Product category 3</th>
      <th>Purchase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @black_fridays.each do |black_friday| %>
      <tr>
        <td><%= black_friday.user_id %></td>
        <td><%= black_friday.product_id %></td>
        <td><%= black_friday.gender %></td>
        <td><%= black_friday.age %></td>
        <td><%= black_friday.occupation %></td>
        <td><%= black_friday.city_category %></td>
        <td><%= black_friday.stay_in_current_city_years %></td>
        <td><%= black_friday.marital_status %></td>
        <td><%= black_friday.product_category_1 %></td>
        <td><%= black_friday.product_category_2 %></td>
        <td><%= black_friday.product_category_3 %></td>
        <td><%= black_friday.purchase %></td>
        <td><%= link_to 'Show', black_friday, :class=>"waves-effect waves-light btn-small" %></td>
        <td><%= link_to 'Edit', edit_black_friday_path(black_friday), :class=>"waves-effect waves-light btn-small" %></td>
        <td><%= link_to 'Destroy', black_friday, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"waves-effect waves-light btn-small" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @black_fridays %>

app/views/black_fridays/new.html.erb
<h3>New Black Friday</h3>

<%= link_to 'Back', black_fridays_path, class: "waves-effect waves-light btn-small" %>

<%= render 'form', black_friday: @black_friday %>

app/views/black_fridays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @black_friday.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @black_friday.product_id %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @black_friday.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @black_friday.age %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @black_friday.occupation %>
</p>

<p>
  <strong>City category:</strong>
  <%= @black_friday.city_category %>
</p>

<p>
  <strong>Stay in current city years:</strong>
  <%= @black_friday.stay_in_current_city_years %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @black_friday.marital_status %>
</p>

<p>
  <strong>Product category 1:</strong>
  <%= @black_friday.product_category_1 %>
</p>

<p>
  <strong>Product category 2:</strong>
  <%= @black_friday.product_category_2 %>
</p>

<p>
  <strong>Product category 3:</strong>
  <%= @black_friday.product_category_3 %>
</p>

<p>
  <strong>Purchase:</strong>
  <%= @black_friday.purchase %>
</p>

<%= link_to 'Edit', edit_black_friday_path(@black_friday), class: "waves-effect waves-light btn" %> |
<%= link_to 'Back', black_fridays_path, class: "waves-effect waves-light btn" %>

app/views/homes/index.html.erb
<h3>Goto</h3>
<%= link_to 'Black Friday Data', black_fridays_path, :class=>"waves-effect waves-light btn-small" %>
<%= link_to 'People Information', pples_path, class: "waves-effect waves-light btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MlApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
     <!-- Page Content goes here -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/pples/index.html.erb
<h1>pple</h1>
<%= link_to 'Back', homes_path, class: "waves-effect waves-light btn" %>